EasyPark/Areas/MyEntryExitManagement/ViewModels/EntryExitManagementViewModel.cs
using EasyPark.Models;
using System.ComponentModel.DataAnnotations;


namespace EasyPark.Areas.MyEntryExitManagement.ViewModel
{
    public class EntryExitManagementViewModel : IValidatableObject
    {
        public int EntryexitId { get; set; }

        [Display(Name="停車場編號")]
        public int? LotId { get; set; }

        [Display(Name = "車輛編號")]
        public int? CarId { get; set; }

        [Display(Name = "預定類型")]
        public string? Parktype { get; set; }

        [Display(Name = "車牌號碼")]
        public string? LicensePlatePhoto { get; set; }

        [Display(Name = "入場時間")]
        public DateTime? EntryTime { get; set; }

        [Display(Name = "繳費時間")]
        public DateTime? LicensePlateKeyinTime { get; set; }

        [Display(Name = "停車費用")]
        public int? Amount { get; set; }

        [Display(Name = "出場時間")]
        public DateTime? ExitTime { get; set; }

        [Display(Name = "繳費狀態")]
        public bool PaymentStatus { get; set; }

        [Display(Name = "付款時間")]
        public DateTime? PaymentTime { get; set; }

        [Display(Name = "逾時時間")]
        public DateTime? ValidTime { get; set; }

        [Display(Name = "完成狀態")]
        public bool IsFinish { get; set; }

        
        public virtual Car? Car { get; set; }

        public virtual ParkingLots? Lot { get; set; }


        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            return new List<ValidationResult>();
        }
    }
}

EasyPark/Models/EntryExitManagement.cs
using System;
using System.Collections.Generic;

namespace EasyPark.Models;

public partial class EntryExitManagement
{
    public int EntryexitId { get; set; }

    public int LotId { get; set; }

    public int CarId { get; set; }

    public string Parktype { get; set; } = null!;

    public string? LicensePlatePhoto { get; set; }

    public DateTime? EntryTime { get; set; }

    public DateTime? LicensePlateKeyinTime { get; set; }

    public int? Amount { get; set; }

    public DateTime? PaymentTime { get; set; }

    public bool PaymentStatus { get; set; }

    public DateTime? ValidTime { get; set; }

    public DateTime? ExitTime { get; set; }

    public bool IsFinish { get; set; }

    public virtual Car? Car { get; set; }

    public virtual ParkingLots? Lot { get; set; }
}

EasyPark/Areas/MyEntryExitManagement/Controllers/EntryExitManagementController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EasyPark.Models;
using EasyPark.Areas.MyEntryExitManagement.ViewModel;
using System.Drawing;
using System.IO;
using System.IO.Pipelines;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.AspNetCore.Authorization;
using System.Globalization;

namespace EasyPark.Areas.MyEntryExitManagement.Controllers
{
    [Authorize]
    [Area("MyEntryExitManagement")]
    public class EntryExitManagementController : Controller
    {
        private readonly EasyParkContext _context;

        public EntryExitManagementController(EasyParkContext context)
        {
            _context = context;
        }

        // GET: MyEntryExitManagement/EntryExitManagement
        public async Task<IActionResult> Index()
        {
            var EasyParkContext = _context.EntryExitManagement.Include(e => e.Car).ThenInclude(e => e.User).Include(e => e.Lot);
            #region 用ViewModel廢用,但先留著而已
            //var entryExitManagements = await _context.EntryExitManagement.ToListAsync();

            //var viewModel = entryExitManagements.Select(e => new EntryExitManagementViewModel
            //{
            //    EntryexitId = e.EntryexitId,
            //    LotId = e.LotId,
            //    CarId = e.CarId,
            //    Parktype = e.Parktype,
            //    LicensePlatePhoto = e.LicensePlatePhoto,
            //    EntryTime = e.EntryTime,
            //    LicensePlateKeyinTime = e.LicensePlateKeyinTime,
            //    Amount = e.Amount,
            //    ExitTime = e.ExitTime,
            //    PaymentStatus = e.PaymentStatus,
            //    PaymentTime = e.PaymentTime,
            //    ValidTime = e.ValidTime,
            //    IsFinish = e.IsFinish,
            //});

            //_viewmodel = viewModel;


            //return View(viewModel);
            #endregion

            // 獲取停車場資料
            var parkingLots = _context.ParkingLots.ToList(); // 假設你有一個 ParkingLots 表

            // 創建一個包含 "全部" 選項的 List
            var parkingLotList = new List<SelectListItem>
            {
                new SelectListItem { Value = "", Text = "全部", Selected=true } // 添加 "全部" 選項
            };

            // 將其他停車場選項添加到 List
            parkingLotList.AddRange(parkingLots.Select(lot => new SelectListItem
            {
                Value = lot.LotId.ToString(),
                Text = lot.LotName
            }));

            // 創建 SelectList
            ViewBag.ParkingLots = new SelectList(parkingLotList, "Value", "Text");

            return View(EasyParkContext);
        }


        #region 圖片預覽和圖片儲存
        public async Task<FileResult> GetPicture(int? id)
        {
            EntryExitManagement? c = await _context.EntryExitManagement.FindAsync(id);
            string? pictureName = c.LicensePlatePhoto;
            var filePath = $"wwwroot\\CarLicense\\_internal\\detected_plates\\{pictureName}";
            var No_filePath = "wwwroot\\images\\not_found.png";

            if (!System.IO.File.Exists(filePath))
            {
                var No_fileStream = new FileStream(No_filePath, FileMode.Open, FileAccess.Read);
                return File(No_fileStream, "image/png");
            }
            else
            {
                var fileStream = new FileStream(filePath, FileMode.Open, FileAccess.Read);
                return File(fileStream, "image/png");
            }            
        }

        private async void SaveUploadImage(EntryExitManagement entryExitManagement, IFormFile Picture)
        {
            if (Picture != null && Picture.Length > 0)
            {
                /*
                using (var memoryStream = new MemoryStream())
                {
                    string Name = Picture.Name;
                    string FileName = Picture.FileName;
                    await Picture.CopyToAsync(memoryStream);
                    entryExitManagement.LicensePlatePhoto = Picture.FileName;
                    Console.WriteLine(Name + FileName );
                    var filename = entryExitManagement.LicensePlatePhoto;
                    var filePath = $"wwwroot\\images\\{filename}.png";

                    using (var fileStream = new FileStream(filePath, FileMode.Create))
                    {
                        await Picture.CopyToAsync(fileStream);
                    }
                }
                */


                // 將圖片文件名儲存到資料庫字段
                entryExitManagement.LicensePlatePhoto = Picture.FileName;
                var filename = entryExitManagement.LicensePlatePhoto;
                var filePath = Path.Combine("wwwroot", "CarLicense\\_internal\\detected_plates", $"{filename}");

                // 直接將圖片複製到指定路徑，而不是使用 MemoryStream
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    await Picture.CopyToAsync(fileStream);
                }
            }
        }

        //0921新增的顯示partialview的aciton
        public async Task<IActionResult> ShowPicturePartial(int id)
        {
            var model = _context.EntryExitManagement.Find(id); // 根據ID查詢資料

            if (model == null)
            {
                return NotFound();
            }

            return PartialView("_ShowPicturePartial", model);

        }

        #endregion

        #region 測試看看如果都改成partial的話
        public async Task<IActionResult> DetailsPartial(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            else
            {

            }

            var entryExitManagement = await _context.EntryExitManagement
                .Include(e => e.Car)
                    .ThenInclude(e => e.User)
                .Include(e => e.Lot)
                .FirstOrDefaultAsync(m => m.EntryexitId == id);

            if (entryExitManagement == null)
            {
                return NotFound();
            }

            return PartialView("_DetailsPartial",entryExitManagement);
        }

        public IActionResult CreatePartial()
        {
            ViewData["CarId"] = new SelectList(_context.Car, "CarId", "LicensePlate");
            ViewData["LotId"] = new SelectList(_context.ParkingLots, "LotId", "LotName");
            ViewData["IsPayment"] = new SelectList(new List<SelectListItem>
            {
                new SelectListItem { Text = "完成", Value = "True" },
                new SelectListItem { Text = "未完成", Value = "False" }
            }, "Value", "Text");

            ViewData["IsFinished"] = new SelectList(new List<SelectListItem>
            {
                new SelectListItem { Text = "完成", Value = "True" },
                new SelectListItem { Text = "未完成", Value = "False" }
            }, "Value", "Text");

            return PartialView("_CreatePartial");
        }

        public async Task<IActionResult> EditPartial(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var entryExitManagement = await _context.EntryExitManagement.FindAsync(id);
            if (entryExitManagement == null)
            {
                return NotFound();
            }
            ViewData["CarId"] = new SelectList(_context.Car, "CarId", "LicensePlate");
            ViewData["LotId"] = new SelectList(_context.ParkingLots, "LotId", "LotName");
            ViewData["IsPayment"] = new SelectList(new List<SelectListItem>
            {
                new SelectListItem { Text = "完成", Value = "True" },
                new SelectListItem { Text = "未完成", Value = "False" }
            }, "Value", "Text", entryExitManagement.PaymentStatus);
            ViewData["IsFinished"] = new SelectList(new List<SelectListItem>
            {
                new SelectListItem { Text = "完成", Value = "True" },
                new SelectListItem { Text = "未完成", Value = "False" }
            }, "Value", "Text", entryExitManagement.IsFinish);

            return PartialView("_EditPartial",entryExitManagement);
        }

        public async Task<IActionResult> DeletePartial(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var entryExitManagement = await _context.EntryExitManagement
                .Include(e => e.Car)
                    .ThenInclude(e => e.User)
                .Include(e => e.Lot)
                .FirstOrDefaultAsync(m => m.EntryexitId == id);

            if (entryExitManagement == null)
            {
                return NotFound();
            }

            return PartialView("_DeletePartial",entryExitManagement);
        }


        #endregion

        #region datatable用ajax的方式生成
        #region 初始GetData方法
        /*
        public IActionResult GetData()
        {

            
            //var data = _context.EntryExitManagement
            //    .Include(e => e.Car) // 加載 Car 資料
            //        .ThenInclude(c => c.User) // 加載 User 資料
            //    .Include(e => e.Lot) // 加載 Lot 資料
            //    .Select(e => new
            //    {
            //        e.EntryexitId,
            //        e.Parktype,
            //        e.LicensePlatePhoto,
            //        CarId = e.Car.LicensePlate, // 假設 LicensePlate 是 Car 的屬性
            //        UserName = e.Car.User.Username, // 來自 User 的名稱
            //        e.EntryTime,
            //        e.LicensePlateKeyinTime,
            //        amount = e.Amount.HasValue ? e.Amount.Value.ToString("C0", CultureInfo.CurrentCulture) : null,
            //        e.ExitTime,
            //        e.PaymentStatus,
            //        e.PaymentTime,
            //        e.ValidTime,
            //        LotName = e.Lot.LotName, // 來自 Lot 的名稱
            //        e.IsFinish
            //    });
            

EasyPark/Areas/MyEntryExitManagement/Views/EntryExitManagement/Create.cshtml
@model EasyPark.Models.EntryExitManagement

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>EntryExitManagement</h4>
<hr />
<div class="row">
    <form asp-action="Create" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="row">
            <div class="col-12 col-lg-4">
                <div class="form-group">
                    <label asp-for="LotId" class="control-label"></label>
                    <select asp-for="LotId" class="form-control" asp-items="ViewBag.LotId"></select>
                    <span asp-validation-for="LotId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CarId" class="control-label"></label>
                    <select asp-for="CarId" class="form-control" asp-items="ViewBag.CarId"></select>
                    <span asp-validation-for="CarId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Parktype" class="control-label"></label>
                    <input asp-for="Parktype" class="form-control" />
                    <span asp-validation-for="Parktype" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="LicensePlatePhoto" class="control-label"></label>
                    <input asp-for="LicensePlatePhoto" class="form-control" />
                    <span asp-validation-for="LicensePlatePhoto" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="EntryTime" class="control-label"></label>
                    <input asp-for="EntryTime" class="form-control" />
                    <span asp-validation-for="EntryTime" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="LicensePlateKeyinTime" class="control-label"></label>
                    <input asp-for="LicensePlateKeyinTime" class="form-control" />
                    <span asp-validation-for="LicensePlateKeyinTime" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Amount" class="control-label"></label>
                    <input asp-for="Amount" class="form-control" />
                    <span asp-validation-for="Amount" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ExitTime" class="control-label"></label>
                    <input asp-for="ExitTime" class="form-control" />
                    <span asp-validation-for="ExitTime" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PaymentTime" class="control-label"></label>
                    <input asp-for="PaymentTime" class="form-control" />
                    <span asp-validation-for="PaymentTime" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ValidTime" class="control-label"></label>
                    <input asp-for="ValidTime" class="form-control" />
                    <span asp-validation-for="ValidTime" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PaymentStatus" class="control-label"></label>
                    <select asp-for="PaymentStatus" class="form-control" asp-items="ViewBag.IsPayment"></select>
                    <span asp-validation-for="PaymentStatus" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="IsFinish" class="control-label"></label>
                    <select asp-for="IsFinish" class="form-control" asp-items="ViewBag.IsFinished"></select>
                    <span asp-validation-for="IsFinish" class="text-danger"></span>
                </div>
            </div>
            <div class="col-12 col-lg-8">
                <div class="d-flex align-content-center justify-content-center my-3">
                    <img style="width:640px;height:480px;" />
                </div>
                <input id="Picture" name="Picture" type="file" accept="image/*" class="form-control" style="width:70%;margin:auto" />
            </div>
        </div>
        <div class="form-group">
            <input type="submit" value="Save" class="btn btn-primary" />
        </div>
    </form>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script src="~/js/picture.js"></script>
}

EasyPark/Areas/MyEntryExitManagement/Views/EntryExitManagement/Delete.cshtml
@model EasyPark.Models.EntryExitManagement

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h2 class="text-bg-danger">確定要刪除嗎?</h2>
<div class="row">
    <h4>EntryExitManagement</h4>
    <hr />
    <div class="col-6">
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Parktype)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Parktype)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.LicensePlatePhoto)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.LicensePlatePhoto)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.EntryTime)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.EntryTime)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.LicensePlateKeyinTime)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.LicensePlateKeyinTime)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Amount)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Amount)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.ExitTime)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.ExitTime)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.PaymentStatus)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PaymentStatus)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.PaymentTime)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PaymentTime)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.ValidTime)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.ValidTime)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.CarId)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.CarId),車主為:@Html.DisplayFor(model => model.Car.User.Username)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.LotId)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.LotId),@Html.DisplayFor(model => model.Lot.LotName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.IsFinish)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.IsFinish)
            </dd>
        </dl>
    </div>
    <div class="col-6">
        <partial name="_ShowPicturePartial" />
    </div>
    <form asp-action="Delete">
        <input type="hidden" asp-for="EntryexitId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

EasyPark/Areas/MyEntryExitManagement/Views/EntryExitManagement/Details.cshtml
@model EasyPark.Models.EntryExitManagement
@* @model MyGoParking.Areas.MyEntryExitManagement.ViewModel.EntryExitManagementViewModel; *@

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>
<h4>EntryExitManagement</h4>
<hr />
<div class="row">
    <div class="col-6">
        <dl class="row">
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Parktype)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Parktype)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.LicensePlatePhoto)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.LicensePlatePhoto)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.EntryTime)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.EntryTime)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.LicensePlateKeyinTime)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.LicensePlateKeyinTime)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.Amount)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.Amount)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.ExitTime)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.ExitTime)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.PaymentStatus)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PaymentStatus)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.PaymentTime)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.PaymentTime)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.ValidTime)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.ValidTime)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.CarId)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.CarId),車主為:@Html.DisplayFor(model => model.Car.User.Username)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.LotId)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.LotId),@Html.DisplayFor(model => model.Lot.LotName)
            </dd>
            <dt class="col-sm-2">
                @Html.DisplayNameFor(model => model.IsFinish)
            </dt>
            <dd class="col-sm-10">
                @Html.DisplayFor(model => model.IsFinish)
            </dd>
        </dl>
    </div>
    <div class="col-6">
        <partial name="_ShowPicturePartial" />
    </div>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.EntryexitId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

EasyPark/Areas/MyEntryExitManagement/Views/EntryExitManagement/Edit.cshtml
@model EasyPark.Models.EntryExitManagement

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>EntryExitManagement</h4>
<hr />
<div class="container">
    <form asp-action="Edit" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <input type="hidden" asp-for="EntryexitId" />
        <div class="row">
            <div class="col-12 col-lg-4">
                <div class="form-group">
                    <label asp-for="LotId" class="control-label"></label>
                    <select asp-for="LotId" class="form-control" asp-items="ViewBag.LotId"></select>
                    <span asp-validation-for="LotId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CarId" class="control-label"></label>
                    <select asp-for="CarId" class="form-control" asp-items="ViewBag.CarId"></select>
                    <span asp-validation-for="CarId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Parktype" class="control-label"></label>
                    <input asp-for="Parktype" class="form-control" />
                    <span asp-validation-for="Parktype" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="LicensePlatePhoto" class="control-label"></label>
                    <input asp-for="LicensePlatePhoto" class="form-control" />
                    <span asp-validation-for="LicensePlatePhoto" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="EntryTime" class="control-label"></label>
                    <input asp-for="EntryTime" class="form-control" />
                    <span asp-validation-for="EntryTime" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="LicensePlateKeyinTime" class="control-label"></label>
                    <input asp-for="LicensePlateKeyinTime" class="form-control" />
                    <span asp-validation-for="LicensePlateKeyinTime" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Amount" class="control-label"></label>
                    <input asp-for="Amount" class="form-control" />
                    <span asp-validation-for="Amount" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ExitTime" class="control-label"></label>
                    <input asp-for="ExitTime" class="form-control" />
                    <span asp-validation-for="ExitTime" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PaymentTime" class="control-label"></label>
                    <input asp-for="PaymentTime" class="form-control" />
                    <span asp-validation-for="PaymentTime" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ValidTime" class="control-label"></label>
                    <input asp-for="ValidTime" class="form-control" />
                    <span asp-validation-for="ValidTime" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="PaymentStatus" class="control-label"></label>
                    <select asp-for="PaymentStatus" class="form-control" asp-items="ViewBag.IsPayment"></select>
                    <span asp-validation-for="PaymentStatus" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="IsFinish" class="control-label"></label>
                    <select asp-for="IsFinish" class="form-control" asp-items="ViewBag.IsFinished"></select>
                    <span asp-validation-for="IsFinish" class="text-danger"></span>
                </div>
            </div>
            <div class="col-12 col-lg-8">
                <div class="d-flex align-content-center justify-content-center my-3">
                    <partial name="_ShowPicturePartial" id="carimg" />
                </div>
                <input id="Picture" name="Picture" type="file" accept="image/*" class="form-control" style="width:70%;margin:auto"/>
            </div>
        </div>
        <div class="form-group">
            <input type="submit" value="Save" class="btn btn-primary"/>
        </div>
    </form>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
    <script>
        $(document).ready(function(){
            $("#IsFinish").on("change", function () { 
                
            })
        })
    </script>
    <script src="~/js/picture.js"></script>
}

EasyPark/Areas/MyEntryExitManagement/Views/EntryExitManagement/_ShowPicturePartial.cshtml
@model EntryExitManagement
@inject EasyParkContext context

@{
    EntryExitManagement? entryExitManagement = await context.EntryExitManagement.FindAsync(Model.EntryexitId);
    if (entryExitManagement != null && entryExitManagement.LicensePlatePhoto != null)
    {
        <div class="d-flex align-content-center justify-content-center align-items-center">
            <img style="width:80%;height:60%;" src="@Url.Action("GetPicture", "EntryExitManagement", new{id=Model.EntryexitId})?t=@DateTime.Now.Ticks" />
        </div>
    }
    else
    {
        <div class="d-flex align-content-center justify-content-center">
        <img src="@Url.Content("~/images/not_found.png")" title="尚無圖片" style="width:640px;height:480px;" />
        </div>
    }
}