EasyPark/Areas/MyMonthlyRental/ViewModels/MonthlyRentalViewModel.cs
using EasyPark.PartailClass;
using System.ComponentModel.DataAnnotations;

namespace EasyPark.Areas.MyMonthlyRental.ViewModels
{
    public class MonthlyRentalViewModel
    {
        //創建表單顯示內容
        [Required(ErrorMessage = "請選擇停車場")]
        [Display(Name = "停車場名稱")]
        public string LotName { get; set; }       

        [Required(ErrorMessage = "請輸入車牌號碼")]
        [CarExists]
        [Display(Name = "車牌號碼")]
        public string LicensePlate { get; set; }

        [Required(ErrorMessage = "請選擇開始日期")]
        [Display(Name = "開始日期")]
        public DateTime StartDate { get; set; }

        [Required(ErrorMessage = "結束日期")]
        [Display(Name = "結束日期")]
        public DateTime EndDate { get; set; }

        public int RenId { get; set; }

        [Display(Name = "月租費用")]
        public int Amount { get; set; }

        [Display(Name = "付款日期")]
        public DateTime? PaymentTime { get; set; }

        [Display(Name = "是否已繳費")]
        public bool PaymentStatus { get; set; }


        //----------之前版本有的

        //[Required(ErrorMessage = "請選擇車位號碼")]
        //[Display(Name = "車位號碼")]
        //public string SlotNumber { get; set; }

        //[Display(Name = "是否已通知")]
        //public bool NotificationStatus { get; set; }


    }
}

EasyPark/Models/MonthlyRental.cs
using System;
using System.Collections.Generic;

namespace EasyPark.Models;

public partial class MonthlyRental
{
    public int RenId { get; set; }

    public int CarId { get; set; }

    public int LotId { get; set; }

    public DateTime? StartDate { get; set; }

    public DateTime? EndDate { get; set; }

    public int Amount { get; set; }

    public bool PaymentStatus { get; set; }

    public string? TransactionId { get; set; }

    public virtual Car Car { get; set; } = null!;

    public virtual ParkingLots Lot { get; set; } = null!;
}

EasyPark/Areas/MyMonthlyRental/Controllers/MonthlyRentalsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using EasyPark.Models;
using EasyPark.Areas.MyMonthlyRental.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace EasyPark.Areas.MyMonthlyRental.Controllers
{
    [Authorize]
    [Area("MyMonthlyRental")]
    public class MonthlyRentalsController : Controller
    {
        private readonly EasyParkContext _context;

        public MonthlyRentalsController(EasyParkContext context)
        {
            _context = context;
        }

        //---------20241107 註解掉的就是過去有的(主要差別在於能不能選車位號碼)

        // GET: MyMonthlyRental/MonthlyRentals
        public async Task<IActionResult> Index()
        {
            var easyParkContext = _context.MonthlyRental.Include(m => m.Car).Include(m => m.Lot);
            return View(await easyParkContext.ToListAsync());

        }

        //Ajax請求:用於產生月租訂單表格
        public async Task<IActionResult> GetRentalData()
        {
            var data = await _context.MonthlyRental
                .Select(m => new
                {
                    Id = m.RenId, // 確保這裡提供 ID
                    lotName = m.Lot.LotName,
                    //slotNumber = m.Slot.SlotNumber,
                    plate = m.Car.LicensePlate,
                    startDate = m.StartDate.HasValue ? m.StartDate.Value.ToString("yyyy-MM-dd") : null,
                    endDate = m.EndDate.HasValue ? m.EndDate.Value.ToString("yyyy-MM-dd") : null,
                    amount = m.Amount,
                    //paymentTime = m.PaymentTime,
                    paymentStatus = m.PaymentStatus == true ? "已付款" : "未付款"
                    //notificationStatus = m.NotificationStatus

                })
                .ToListAsync();

            return Json(data);
        }


        // GET: MyMonthlyRental/MonthlyRentals/Create
        public async Task<IActionResult> Create()
        {
            var viewModel = new MonthlyRentalViewModel
            {
                StartDate = DateTime.Now.Date,  // 設置開始日期為當前日期
                EndDate = DateTime.Now.Date.AddMonths(1)  // 預設結束日期為開始日期加一個月
            };
            ViewData["LotName"] = new SelectList(_context.ParkingLots, "LotName", "LotName");
            // 建立空白下拉式選單(車位號碼)
            //ViewData["SlotNumber"] = new SelectList(new List<SelectListItem>());  
            return View(viewModel);

        }


        // POST: MyMonthlyRental/MonthlyRentals/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(MonthlyRentalViewModel viewModel)
        {
            if (ModelState.IsValid)
            {

                var lotId = _context.ParkingLots
                    .Where(n => n.LotName == viewModel.LotName)
                    .Select(n => n.LotId)
                    .FirstOrDefault();

                //20241107 Slot Number改成沒有指定(優先分配該停車場第一個空位)
                var SlotId = _context.ParkingSlot
                    .Where(n => n.LotId == lotId && n.IsRented == false)
                    .Select(n => n.SlotId)
                    .FirstOrDefault();

                var monthlyRental = new MonthlyRental
                {
                    LotId = lotId,
                    //SlotId = SlotId,   //20241107 原本有指定車位後來沒有
                    CarId = _context.Car
                    .Where(n => n.LicensePlate == viewModel.LicensePlate)
                    .Select(n => n.CarId)
                    .FirstOrDefault(),

                    StartDate = viewModel.StartDate,
                    EndDate = viewModel.EndDate,
                    Amount = 3000, //預設值
                    PaymentStatus = true,
                };

                // 使用 slotId 查詢車位
                var updateSlot = _context.ParkingSlot
                    .FirstOrDefault(slot => slot.SlotId == SlotId);
                //更新該車位狀態為被預訂
                updateSlot.IsRented = true;

                //查詢停車場(要變更月租車位剩餘數量)
                var updateLot = _context.ParkingLots
                    .FirstOrDefault(lot => lot.LotId == lotId);

                //月租車位數-1
                updateLot.MonRentalSpace -= 1;

                //更新資料表
                await _context.SaveChangesAsync();

                _context.Add(monthlyRental);
                await _context.SaveChangesAsync();
                return Json(new { success = true });
            }
            else
            {
                var errors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage).ToList();
                return Json(new { success = false, errors });
            }

        }


        // GET: MyMonthlyRental/MonthlyRentals/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }


            var monthlyRental = await _context.MonthlyRental.FindAsync(id);
            if (monthlyRental == null)
            {
                return NotFound();
            }

            string lotName = await _context.ParkingLots.Where(lot => lot.LotId == monthlyRental.LotId).Select(lot => lot.LotName).FirstOrDefaultAsync();
            //string slotNumber = await _context.ParkingSlot.Where(slot => slot.SlotId == monthlyRental.SlotId).Select(slot => slot.SlotNumber).FirstOrDefaultAsync();
            string license = await _context.Car.Where(car => car.CarId == monthlyRental.CarId).Select(car => car.LicensePlate).FirstOrDefaultAsync();
            var viewModel = new MonthlyRentalViewModel
            {
                RenId = monthlyRental.RenId,
                LotName = lotName,
                //SlotNumber = slotNumber,
                LicensePlate = license,
                StartDate = (DateTime)monthlyRental.StartDate,
                EndDate = (DateTime)monthlyRental.EndDate,
                Amount = (int)monthlyRental.Amount,
                //PaymentTime = monthlyRental.PaymentTime,
                PaymentStatus = monthlyRental.PaymentStatus,
                //NotificationStatus = monthlyRental.NotificationStatus,

            };
            //新增的
            ViewData["LotName"] = new SelectList(_context.ParkingLots, "LotName", "LotName");
            // 建立空白下拉式選單(車位號碼)
            //ViewData["SlotNumber"] = new SelectList(new List<SelectListItem>());  

            return View(viewModel);

        }



        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, MonthlyRentalViewModel viewModel)
        {
            if (id != viewModel.RenId)
            {
                return NotFound();
            }

            var lotId = _context.ParkingLots
                    .Where(n => n.LotName == viewModel.LotName)
                    .Select(n => n.LotId)
                    .FirstOrDefault();

            var carId = _context.Car
                    .Where(n => n.LicensePlate == viewModel.LicensePlate)
                    .Select(n => n.CarId)
                    .FirstOrDefault();

            if (ModelState.IsValid)
            {
                try
                {
                    // 從 ViewModel 轉換為 MonthlyRental
                    var monthlyRental = new MonthlyRental
                    {
                        RenId = viewModel.RenId,
                        LotId = lotId,
                        CarId = carId,
                        //SlotId = SlotId,
                        StartDate = viewModel.StartDate,
                        EndDate = viewModel.EndDate,
                        //RenewalStatus = false,
                        //NotificationStatus = viewModel.NotificationStatus,
                        Amount = viewModel.Amount,
                        //PaymentTime = viewModel.PaymentTime,
                        PaymentStatus = viewModel.PaymentStatus
                    };

                    _context.Update(monthlyRental);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MonthlyRentalExists(viewModel.RenId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return Json(new { success = true });
            }
            else
            {
                var errors = ModelState.Values.SelectMany(v => v.Errors).Select(e => e.ErrorMessage).ToList();
                return Json(new { success = false, errors });
            }

        }
        

        private bool MonthlyRentalExists(int id)
        {
            return _context.MonthlyRental.Any(e => e.RenId == id);
        }
    }
}

EasyPark/Areas/MyMonthlyRental/Views/MonthlyRentals/Create.cshtml
@* @model EasyPark.Models.MonthlyRental *@
@model EasyPark.Areas.MyMonthlyRental.ViewModels.MonthlyRentalViewModel;

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>MonthlyRental</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" id="CreateForm" class="col-md-12">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="LotName" class="control-label"></label>
                <select asp-for="LotName" id="selectLotName" class="form-control" asp-items="ViewBag.LotName"></select>
            </div>

@*             <div class="form-group">
                <label asp-for="SlotNumber" class="control-label"></label>
                <select asp-for="SlotNumber" id="SelectSlotNumber" class="form-control" asp-items="ViewBag.SlotNumber"></select>
            </div> *@

            @* 暫時改輸入框 成功後要刪除這串 *@
            <div class="form-group">
                <label asp-for="LicensePlate" class="control-label"></label>
                <input asp-for="LicensePlate" class="form-control" />
                <span asp-validation-for="LicensePlate" class="text-danger"></span>
            </div>

            @* 嘗試改回下拉式選單，根據選擇停車場自動帶入車位 *@
            @* ViewData["SlotNumber"] = new SelectList(_context.ParkingSlot, "Value", "Text") *@

            @*             <div class="form-group">
            <label asp-for="LicensePlate" class="control-label"></label>
            <select asp-for="LicensePlate" class ="form-control"></select>
            <span asp-validation-for="LicensePlate" class="text-danger"></span>
            </div> *@
            <div class="form-group">
                <label asp-for="StartDate" class="control-label"></label>
                <input asp-for="StartDate" class="form-control" />
                <span asp-validation-for="StartDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EndDate" class="control-label"></label>
                <input asp-for="EndDate" class="form-control" />
                <span asp-validation-for="EndDate" class="text-danger"></span>
            </div>
            @* <div class="form-group form-check">
            <label class="form-check-label">
            <input class="form-check-input" asp-for="RenewalStatus" /> @Html.DisplayNameFor(model => model.RenewalStatus)
            </label>
            </div>
            <div class="form-group form-check">
            <label class="form-check-label">
            <input class="form-check-input" asp-for="NotificationStatus" /> @Html.DisplayNameFor(model => model.NotificationStatus)
            </label>
            </div>
            <div class="form-group">
            <label asp-for="Amount" class="control-label"></label>
            <input asp-for="Amount" class="form-control" />
            <span asp-validation-for="Amount" class="text-danger"></span>
            </div> *@
            @*             <div class="form-group">
            <label asp-for="PaymentTime" class="control-label"></label>
            <input asp-for="PaymentTime" class="form-control" />
            <span asp-validation-for="PaymentTime" class="text-danger"></span>
            </div>
            <div class="form-group form-check">
            <label class="form-check-label">
            <input class="form-check-input" asp-for="PaymentStatus" /> @Html.DisplayNameFor(model => model.PaymentStatus)
            </label>
            </div> *@
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

EasyPark/Areas/MyMonthlyRental/Views/MonthlyRentals/Delete.cshtml
@model EasyPark.Models.MonthlyRental

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>MonthlyRental</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PaymentStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PaymentStatus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TransactionId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TransactionId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Car)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Car.CarId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Lot)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Lot.LotId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="RenId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

EasyPark/Areas/MyMonthlyRental/Views/MonthlyRentals/Details.cshtml
@model EasyPark.Models.MonthlyRental

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>MonthlyRental</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.StartDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.StartDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EndDate)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EndDate)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PaymentStatus)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PaymentStatus)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TransactionId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TransactionId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Car)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Car.CarId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Lot)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Lot.LotId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.RenId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

EasyPark/Areas/MyMonthlyRental/Views/MonthlyRentals/Index.cshtml
@model IEnumerable<EasyPark.Models.MonthlyRental>

@{
    ViewData["Title"] = "Index";
}

@section Styles {
    <!-- Tabulator 的樣式 -->
    <link href="https://cdn.jsdelivr.net/npm/tabulator-tables@5.0.7/dist/css/tabulator.min.css" rel="stylesheet">
    <style>

        #parking-table{
            border:none;
        }

        .tabulator-col {
            background-color: white !important;
            color: black;
            font-size: 16px;
            text-align: center;
            border:none !important;
        }

        .tabulator-row {
            background-color: white !important;
        }

            .tabulator-row:hover {
                background-color: lightgray !important;
            }

        .tabulator-cell {
            border-top: none !important;
            border-left: none !important;
            border-right: none !important;
            border-bottom: 1px solid #ccc !important; /* 下方格線 */
        }
    </style>
}

<h1>月租管理</h1>

<div class="d-flex justify-content-between align-item-center mb-3">
    <button type="button" id="CreateBtn" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#myModal">
        <i class="fa-solid fa-folder-plus fa-beat-fade"></i> 新增
    </button>
    <input type="text" id="searchRental" placeholder="請輸入關鍵字">
</div>

<div id="date-filter-panel">
    <label for="startDate-filter">開始日期：</label>
    <input type="date" id="startDate-filter">
    <label for="endDate-filter">結束日期：</label>
    <input type="date" id="endDate-filter">
    <button id="apply-date-filter">篩選日期</button>
</div>

<!-- Tabulator表格容器 -->
<div id="parking-table"></div>
<div class="mt-1" id="record-count">總筆數: 0</div>


<!-- Create Modal -->
<div class="modal fade" id="myModal" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">新增</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="yooo">
                <!-- 這裡會載入 #CreateForm 的內容 -->
            </div>

        </div>
    </div>
</div>

<!-- Edit Modal -->
<div class="modal fade" id="RentalEditModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">編輯</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="nooo">
                ...
            </div>
        </div>
    </div>
</div>


@section Scripts
{
    <script src="https://cdn.jsdelivr.net/npm/tabulator-tables@5.0.7/dist/js/tabulator.min.js"></script>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        document.addEventListener("DOMContentLoaded", function () {
            // 初始化 Tabulator
            var table = new Tabulator("#parking-table", {
                ajaxURL: "@Url.Action("GetRentalData", "MonthlyRentals")",
                columns: [
                    { title: "停車場名稱", field: "lotName", width: 200, headerFilter: "input" },
                    // { title: "車位號碼", field: "slotNumber", width: 100, headerFilter: "input" },
                    { title: "車牌號碼", field: "plate", width: 200, headerFilter: "input" },
                    { title: "開始日期", field: "startDate", width: 200 },
                    { title: "結束日期", field: "endDate", width: 200 },
                    { title: "月租費用", field: "amount", width: 200 },
                    // { title: "付款日期", field: "paymentTime", width: 150 },
                    { title: "付款狀態", field: "paymentStatus", width: 150, headerFilter: "select", headerFilterParams: { 已付款: "已付款", 未付款: "未付款" } },  // 下拉選單篩選器 },
                    // { title: "通知狀態", field: "notificationStatus", width: 100 },
                    {
                        title: "Actions",
                        field: "actions",
                        width: 150,
                        hozAlign: "center",
                        formatter: function (cell, formatterParams, onRendered) {
                            var id = cell.getRow().getData().id;
                            console.log(id)
                            return `<button type="button" class="RentalEditBtn btn" data-id="${id}" data-bs-toggle="modal" data-bs-target="#RentalEditModal"><i class="fa-regular fa-pen-to-square mr-1" style="font-size:18px"></i></button>`;
                        }
                    }
                ],
                pagination: "local",
                paginationSize: 10,
                paginationSizeSelector: [10, 25, 50, 100],
                rowClick: function (e, row) {
                    console.log("Row clicked:", row.getData());
                },
                ajaxResponse: function (url, params, response) {
                    // 當資料加載完成後顯示總筆數
                    updateRecordCount(response.length);
                    return response;
                },
                dataFiltered: function (filters, rows) {
                    // 篩選資料後顯示篩選後的總筆數
                    updateRecordCount(rows.length);
                }
            });

            // 監聽篩選後更新筆數
            table.on("dataFiltered", function (filters, rows) {
                updateRecordCount(rows.length);
            });

            // 訂單搜尋功能(暫時不用)
            $("#searchRental").on("keyup", function () {
                console.log(this.value);
                table.setFilter("lotName", "like", this.value);
                table.setFilter("plate", "like", this.value);
                // 更新筆數
                updateRecordCount(table.getData().length);
            });

            // 日期篩選功能
            $("#apply-date-filter").on("click", function () {
                var startDate = $("#startDate-filter").val();
                var endDate = $("#endDate-filter").val();
                // 更新筆數
                table.on("dataFiltered", function (data) {
                    updateRecordCount(data.length);
                });
                table.setFilter(function (data) {
                    // 將 datetime 轉換為只包含日期部分的 yyyy-mm-dd
                    var dataStartDate = new Date(data.startDate).setHours(0, 0, 0, 0);  // 將時間設為 00:00:00
                    var dataEndDate = new Date(data.endDate).setHours(0, 0, 0, 0);  // 將時間設為 00:00:00

                    var filterStartDate = startDate ? new Date(startDate).setHours(0, 0, 0, 0) : null;
                    var filterEndDate = endDate ? new Date(endDate).setHours(0, 0, 0, 0) : null;

                    return (!startDate || dataStartDate >= filterStartDate) && (!endDate || dataEndDate <= filterEndDate);
                });

            });

            // 更新總筆數的函數
            function updateRecordCount(count) {
                document.getElementById("record-count").innerText = "總筆數: " + count;
            }
        });

            // 動態加載 Create 內容
            $('#CreateBtn').on('click', function () {
                // 先載入模態視窗內容
                $('#yooo').load('/MyMonthlyRental/MonthlyRentals/Create #CreateForm', function () {
                    // 確保模態視窗顯示
                    $('#myModal').modal('show');

                    // 設定表單的提交事件
                    $('#CreateForm').on('submit', function (e) {
                        e.preventDefault(); // 防止默認提交行為
                        $.ajax({
                            url: $(this).attr('action'), // 表單的 action URL
                            type: 'POST',
                            data: $(this).serialize(), // 將表單數據序列化
                            dataType: 'Json',
                            success: function (response) {
                                if (response.success) {
                                    // 如果成功，關閉模態視窗，並刷新頁面或局部刷新
                                    $('#myModal').modal('hide');
                                    location.reload(); // 刷新特定部分
                                } else {
                                    // 如果失敗，動態替換SweetAlert，顯示錯誤
                                    Swal.fire({
                                        icon: "error",
                                        title: "Oops...",
                                        text: response.errors.join(", "),
                                    });
                                }
                            },
                            error: function (xhr, status, error) {
                                console.log('Error:', error);
                            }
                        });
                    });

                    //當選擇停車場改變，可選車位亦要更動
                    $('#selectLotName').on('change', function () {
                            
                    });

                });
            });


            //動態加載edit內容
            $(document).on('click', '.RentalEditBtn', function () {
                var id = $(this).data('id');
                console.log(id);
                $('#nooo').load(`/MyMonthlyRental/MonthlyRentals/Edit/${id} #RentalEditForm`, function (response, status, xhr) {
                    if (status == "success") {
                        var lotNameFromResponse = $(response).find('#selectLotName').val();
                        // var slotNumberFromResponse = $(response).find('#SelectSlotNumber').val();
                        console.log("Lot Name from response:", lotNameFromResponse);
                        // console.log(slotNumberFromResponse);

                        // 設置選擇的停車場名稱
                        $('#selectLotName').val(lotNameFromResponse).trigger('change');
                        // loadSlotsByLotName(lotNameFromResponse, slotNumberFromResponse);
                        $(document).on('submit', '#RentalEditForm', function (e) {
                            e.preventDefault(); // 防止默認提交行為
                            $.ajax({
                                url: $(this).attr('action'), // 表單的 action URL
                                type: 'POST',
                                data: $(this).serialize(), // 將表單數據序列化
                                dataType: 'json',
                                success: function (response) {
                                    if (response.success) {
                                        console.log("12313")
                                        // 如果成功，關閉模態視窗，並刷新頁面或局部刷新
                                        $('#ApplyEditModal').modal('hide');
                                        location.reload(); // 刷新特定部分
                                    } else {
                                        // 如果失敗，動態替換SweetAlert，顯示錯誤
                                        Swal.fire({
                                            icon: "error",
                                            title: "Oops...",
                                            text: response.errors.join(", "),
                                        });
                                    }
                                }
                            });
                        });
                    }
                    $('#ApplyEditModal').modal('show');


                    //當選擇停車場改變，可選車位亦要更動
                    $('#selectLotName').on('change', function () {                            
                    });


                });
            });


                





    </script>

}